### ISSUE TITLE
"Extracted app sharingpath has more than 1 folder"

### ISSUE THREAD

**Issue by schniepp** [rookie0/nextcloud-sharing-path#1]
I just tried to install the app from the appstore and got the above error message.
I did not see any folder related to the app in the "apps" folder.

**Comment by rookie0** [comment]
Sorry, I didn't realized OS X's tar uses the AppleDouble format to store extended attributes and ACLs, it will put ._filename in tar archives.

I have fixed this and updated the package, but you may need clear Nextcloud app store cache by remove the file /your-nextcloud-path/data/appdata_xxxx/appstore/apps.json to avoid invalid signature error.

**Comment by schniepp** [comment]
Cool, it works now!
I did not have any folder  /your-nextcloud-path/data/ or any file "apps.json" in my NC installation path. 

So where do I put the files to be shared? Which files are going to be shared? I did not find any settings/options.

**Comment by rookie0** [comment]
`/your-nextcloud-path/data/appdata_xxxx/appstore/apps.json` is the app store cache file, never mind.

Navigate to your Nextcloud `All files` page, just add a share link(click share icon) in the list file without password protect, then click the more icon `···` choose `Open Sharing Path`, next open tab page url is the direct link you can access.

Later i will put more usage info in README.
