### ISSUE TITLE
cannot create link to file

### ISSUE THREAD

**Issue by hele333** [rookie0/nextcloud-sharing-path#10]
Thanks for your app, we appreciate working with it :-)
In a former version (NC13) we were able to share files which are in a shared folder.
Now using NC17 ( 17.0.1) with your app 0.0.3 I get an error. By right-click the file "Copy sharing path" your app responses "no shared links" even the folder or the file by itself is shared.

Is there a special way, how the files have to be shared?
Thanks for any response.

**Comment by rookie0** [comment]
Please check your share way, shared files can only be accessed by share link and do not check `Hide download` or `Password protect`.

**Comment by hele333** [comment]
thanks for the info, yes that is working.
Is there a way to share a folder by link and use "sharing path" for the files in the folder, without sharing the single files explicitly?

**Comment by rookie0** [comment]
Yeah, will take a look.

**Comment by rookie0** [comment]
Released in [v0.1.0](https://github.com/rookie0/nextcloud-sharing-path/releases/tag/v0.1.0).
