### ISSUE TITLE
Link return null

### ISSUE THREAD

**Issue by nuocgansoi** [rookie0/nextcloud-sharing-path#12]
version: Nextcloud 18
system: Ubuntu 18.04

Sharing path link return only "null" text, and do not show any think.

This is my sharing link:
https://cloud.quychan.com/s/Q43PW7xbbjNs6LC

And sharing path link:
https://cloud.quychan.com/apps/sharingpath/datdang/Images/be128307cbd37847e2a3daa04ffa0133.jpg

**Comment by rookie0** [comment]
![image](https://user-images.githubusercontent.com/5813232/76695898-bb934900-66bf-11ea-9fe6-ece28c76a74e.png)
Please recheck.
