### ISSUE TITLE
Issues sharing Text files.

### ISSUE THREAD

**Issue by sinalta** [rookie0/nextcloud-sharing-path#13]
Nextcloud version: 18.0.3 (Within a Docker image)
App version: 0.2.0

I'm seeing 2 issues when trying to share text files:

1. A short test text file I made doesn't seem to be working at all. It's contents is simply "test text file" and when shared normally this downloads as expected, but doesn't load at all when accessed via sharing path. This file was made in an attempt to test issue 2.

2. A JSON file I'd like to be able to download into another application is being appended with "null" which is causing an error when tryng to parse it. Null is not there when it is uploaded or downloaded via a standard sharing link, only when accessed via sharing path. Line endings are Unix style.

Is there anything I can do to workaround this second issue?
I can provide links to the files in a private message if needed, but I'd rather not post them publically.

**Comment by rookie0** [comment]
1. You can check the nextcloud.log grep by sharingpath(v0.2.1 or v0.2.0 use "request user") for the detail, may be nothing.

2. Fixed in [v0.2.1](https://github.com/rookie0/nextcloud-sharing-path/releases/tag/v0.2.1).

**Comment by sinalta** [comment]
1. I don't see anything in the log for it, but it's stopped happening now and the file loads fine. So it might have just been an issue with my server itself.
2. I just installed it and can confirm it's fixed! Thankyou very much.

**Comment by rookie0** [comment]
My pleasure.
