### ISSUE TITLE
Set specific Content-Type headers

### ISSUE THREAD

**Issue by juniperrrrr** [rookie0/nextcloud-sharing-path#17]
Love it!! Buuut there's one problem.. the `Content-Type` headers are set to `application/json; charset=utf-8`. Is it possible to check the file and set it to `video/mp4` or `audio/mpeg`?

**Comment by rookie0** [comment]
In fact, it is check the file and set the [`Content-Type`](https://github.com/rookie0/nextcloud-sharing-path/blob/master/lib/Controller/PathController.php#L194), please check your file real type.
![image](https://user-images.githubusercontent.com/5813232/81764719-bf4b1c80-9504-11ea-96c4-86615a2cc82d.png)

**Comment by juniperrrrr** [comment]
It shows video/mp4 in a browser but still application/json when using curl please check :(

![image](https://user-images.githubusercontent.com/65240111/84539902-5650f300-acc2-11ea-9dec-e83240512be3.png)

**Comment by rookie0** [comment]
Fixed in [v0.2.4](https://github.com/rookie0/nextcloud-sharing-path/releases/tag/v0.2.4)
