### ISSUE TITLE
Sharing path doen't work for folders

### ISSUE THREAD

**Issue by itsequans** [rookie0/nextcloud-sharing-path#18]
Hi,

In Nextcloud 18.0.4, the sharing path doesn't work for folders:
- When I click the 3 points menu I don't see the "Copy Sharing Path" entry as I see it for files
- If my folder is shared and I access its link as it would be built by sharing path i go nowhere.
  I'm nor denied, I'm just downloading an empty file

**Comment by rookie0** [comment]
Please check https://github.com/rookie0/nextcloud-sharing-path/issues/14#issuecomment-616262609
