### ISSUE TITLE
File not found. When trying to share .mp4 file

### ISSUE THREAD

**Issue by madmatuk** [rookie0/nextcloud-sharing-path#2]
Just what i need, working for images, but trying an .mp4 video file give me the error : `File not found.` when viewing the link.

**Comment by rookie0** [comment]
Please share your file first, check [Usage](https://github.com/rookie0/nextcloud-sharing-path#usage)

**Comment by madmatuk** [comment]
Yup - I shared the file, as i did with images, then clicked the Open sharing path which takes me to what i would expect to be the correct URL - however i get the File not found error. Images work just fine. Strange

**Comment by rookie0** [comment]
Sorry, cant figure out, next version i will add some error log.
