### ISSUE TITLE
Cannot embed in external websites

### ISSUE THREAD

**Issue by TheNomad11** [rookie0/nextcloud-sharing-path#22]
Very useful plugin, thanks alot. Accessing the file / image/ video via the URL in the browser works fine, but embedding it in an external website does not. I tried to embed a video on Wordpress site and also tried adding an image via plain html code, but the image or video cannot be accessed in this case. I wonder if it is a security feature by Nextcloud or not? Thanks!

**Comment by rookie0** [comment]
Fixed in [v0.2.3](https://github.com/rookie0/nextcloud-sharing-path/releases/tag/v0.2.3).

And if it's not works, maybe you need change some headers like `Content-Security-Policy` in your `nginx.conf`.
