### ISSUE TITLE
Getting null files through Sharing Path folder when already logged in.

### ISSUE THREAD

**Issue by GeneriumMadness** [rookie0/nextcloud-sharing-path#23]
When I am logged in and trying to get file from another user I get only 0kb empty file. But when I log out from the site file becomes available for correct download.

**Comment by rookie0** [comment]
Maybe there is a bug like #12 , please give me some detail, check your `NEXTCLOUD-INSTALL-PATH/data/nextcloud.log` grep by `"app":"sharingpath"` and your web server log grep by request path.

**Comment by GeneriumMadness** [comment]
![image](https://user-images.githubusercontent.com/29273152/86745773-41f2e280-c043-11ea-95e8-3de7682f6523.png)

https://vk.com/away.php?utf=1&to=https%3A%2F%2Fown-drive.ru%2Fapps%2Fsharingpath%2FMcPaRaDoX%2FBHPfDDNOKhQ.jpg

https%3A%2F%2Fown-drive.ru%2Fs%2FrTz4CJrndLcbktY

**Comment by rookie0** [comment]
Sorry for the late reply, i can't reproduce the problem, and my guess is that my app or nextcloud get wrong user info, but my app get username from url path, it can't be wrong. 

It's so confusing, and i will still look into it.

**Comment by imgoodplanner** [comment]
I have same issue.
browser request favicon.ico and login. 
![image](https://user-images.githubusercontent.com/46765159/89115382-aed28e80-d4c2-11ea-9d7b-a48d1c5f6fb8.png)

**Comment by rookie0** [comment]
@imgoodplanner It's not a big deal, and do not affect the use of this app, if you are worried about it, you can put a `favicon.ico` file at `YOUR-NEXTCLOUD-INSTALL-PATH`.

**Comment by GeneriumMadness** [comment]
Quick steps to reproduce:
1. Install 2 different browsers or open one tab in incognito mode
2. Log in with 2 different accounts in these tabs/browsers
3. Share any file (i tried with picture) and copy sharing path link
4. Use this link in another tab/browser
5. It should get you null file
https://own-drive.ru/index.php/s/j7g6TSxCCxPgxJp
there is a video how I reproduced this problem
