### ISSUE TITLE
Spaces formatting in URL

### ISSUE THREAD

**Issue by theosche** [rookie0/nextcloud-sharing-path#24]
If there is a space in the name of the file (or any parent folder) I want to share, then the link I get includes these space characters. Space characters should be replaced by "%20" so that links are correctly recognized.

For example I should not get:
https://cloud.domain.com/index.php/apps/sharingpath/user/Parent name/file name.docx

But:
https://cloud.domain.com/index.php/apps/sharingpath/user/Parent%20name/file%20name.docx

**Comment by rookie0** [comment]
Sorry for the late reply, fixed in [v0.2.5](https://github.com/rookie0/nextcloud-sharing-path/releases/tag/v0.2.5).
