### ISSUE TITLE
Version 20 Compatibility

### ISSUE THREAD

**Issue by sunjam** [rookie0/nextcloud-sharing-path#25]
Please update for version 20 compatibility.  Thanks!

**Comment by amirhmoradi** [comment]
Thanks @rookie0  for this great nextcloud app!
Please provide a nextcloud 20 compatible version. 
I tried to dig into the code, but I could not understand why this does not work with nextcloud 20.

**Comment by rookie0** [comment]
Sorry for my late response, cause i have been busy lately, and nextcloud 20 has a lot of changes that may take some time to upgrade, but i will do it ASAP, please be patient.

**Comment by rookie0** [comment]
Sorry, finally updated [0.3.0](https://github.com/rookie0/nextcloud-sharing-path/releases/tag/v0.3.0)
