### ISSUE TITLE
Make it default to disabled

### ISSUE THREAD

**Issue by jsalatiel** [rookie0/nextcloud-sharing-path#26]
Please make it default to **disabled** in settings.
That would improve security a lot since only power users and those who knew what sharingpath is would enable that setting.

**Comment by rookie0** [comment]
Fixed in [0.3.0](https://github.com/rookie0/nextcloud-sharing-path/releases/tag/v0.3.0)

**Comment by sushibear** [comment]
Hey...  thanks for this great plugin but I don't agree with this change completely.
Wouldn't it be possible to make this feature either way..  like the admin can force this to be **on** for all as default but each user can turn it off if he likes? 
We would like this to be **on** for every new user we create using the Nextcloud API and since Apps can not be configured that way, we have no chance to do this, unless we would create a fork, which I think is not the way to go.

Regards

**Comment by rookie0** [comment]
Maybe add an admin setting `Default enable sharingpath`, and this may go with #16 which i intend to add an admin setting `Default sharing directory`.
What do u think? @sushibear

**Comment by sushibear** [comment]
> Maybe add an admin setting `Default enable sharingpath`, and this may go with #16 which i intend to add an admin setting `Default sharing directory`.

Hey..  thanks for reopening this ticket and looking into this! I think `Default enable sharingpath` is exactly what we need even though I don't know what `Default sharing directory` would look like. I mean the current path is like: `https://mydomain/apps/sharingpath/username/shared/folder/filename.png`
What would the path look like with the default setting?

Regards

**Comment by rookie0** [comment]
Now you must share the file first before you can access it by sharingpath, the `Default sharing directory` is a setting which you can set a specific folder that  the files in the folder can be accessed by sharingpath no matter you shared or not.

**Comment by sushibear** [comment]
> Now you must share the file first before you can access it by sharingpath, the `Default sharing directory` is a setting which you can set a specific folder that the files in the folder can be accessed by sharingpath no matter you shared or not.

I understand..  hmmm..  but that would be another feature beside the `Default enable sharing` by the admin right?

**Comment by rookie0** [comment]
Yeah, will done in 2020. 😄

**Comment by sushibear** [comment]
Thanks man! You Rock!

**Comment by rookie0** [comment]
@sushibear  [v0.4.0 - nightly](https://github.com/rookie0/nextcloud-sharing-path/releases/tag/v0.4.0) Please take a look.

**Comment by sushibear** [comment]
@rookie0 looking great man!! Good work!!
