### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by hexclann** [rookie0/nextcloud-sharing-path#27]
I have Nextcloud 20.0.1 and sharing path app 0.3.0 installed on a Linux machine with PHP 7.4. Admin and I have both have enabled the sharing path in  `Settings` > `Personal` > `Sharing` but when I click on the share option, the link will be the same as before - https://example.com/index.php/s/M8WaJ6BPn4Mx75G. I have not enabled any options in the sharing menu like expiration date etc. And I don't have any setup or security warnings

**Comment by rookie0** [comment]
![image](https://user-images.githubusercontent.com/5813232/99206883-73e93200-27f7-11eb-9953-7fb307042688.png)
Please check you copy the path in right place.
