### ISSUE TITLE
[feature] request that the prefix can be customized in the settings.

### ISSUE THREAD

**Issue by medivh-jay** [rookie0/nextcloud-sharing-path#28]
Expect to add a setting function to replace  `https://youre-domain/nextcloud/apps/sharingpath/username/` when copying, For example, `https://youre-domain/nextcloud/apps/sharingpath/username/a.jpg`, after the custom prefix is `https://oss.domian.com/`， the copied path is  `https://oss.domian.com/a.jpg`

**Comment by GeneriumMadness** [comment]
Imagine that you have 2 users and they has opened access to the file "a.jpg". Which one file will be selected when you will follow the link?

**Comment by rookie0** [comment]
I'm agree with @GeneriumMadness, there maybe can add an admin setting like `Sharingpath copy prefix` for the host part `https://oss.domian.com`, but can not ignore the `username`.

Or you can add an nginx(apache...) rewrite rule for some special user. @medivh-jay

**Comment by medivh-jay** [comment]
Yes, I did use nginx rewrite, because I think this setting belongs to the user setting, not the system setting. If multiple users use it, they can choose to perform their own nginx rewrite operation on their own path containing the username.  
![image](https://user-images.githubusercontent.com/23169872/102169596-85445d80-3ecd-11eb-8272-77a496399e24.png)

**Comment by rookie0** [comment]
@medivh-jay Got it, will do.

**Comment by medivh-jay** [comment]
Thank you very much for your contribution ![image](https://user-images.githubusercontent.com/23169872/102189431-9606ca80-3ef1-11eb-81a0-9377fa7798f8.png)

**Comment by rookie0** [comment]
@medivh-jay [v0.4.0 - nightly](https://github.com/rookie0/nextcloud-sharing-path/releases/tag/v0.4.0) Please take a look.

**Comment by medivh-jay** [comment]
@rookie0 AWESOME! Thank you very much for your changes to this feature. 
![sharingpath](https://user-images.githubusercontent.com/23169872/103392994-6b587b00-4b5b-11eb-9f63-aabdc5759b10.png)
