### ISSUE TITLE
Still have the same issue that the endless 302 redirect happens

### ISSUE THREAD

**Issue by SakuraLove** [rookie0/nextcloud-sharing-path#3]
I tried to use nextcloud as a CDN server which is also what this plugin doing.
When I was using the official function, adding "/download" at the end of the share link and put it in the video tag in a web page, it will cause an endless 302 redirect as what this issue is talking about.
https://github.com/nextcloud/server/issues/542

So I tried this plugin, but still, the endless 302 redirects are still happening. So I wanna check if there is any way to fix this problem.

**Comment by rookie0** [comment]
Please check the sharing path can be accessed first.

Then check your access.log to find the request detail, maybe failed at CDN and did not reach your nextcloud server.

**Comment by SakuraLove** [comment]
Yes, the link cloud be accessed by a browser, or be downloaded directly, but when I embed it in the video tag in html, it will show an endless 302 redirect. I think this is because of the nextcloud itself.

**Comment by SakuraLove** [comment]
You could check this issue in NextCloud repo to see, https://github.com/nextcloud/server/issues/542

**Comment by SakuraLove** [comment]
哦 我懂你意思了，这个插件是把NextCloud当成CDN源站用。我以为是用于创建直链分享的。想多了hh

**Comment by SakuraLove** [comment]
NextCloud文件分享+/download的直链扔在html的video标签无法查看，会导致循环302。只能想其他办法解决了

**Comment by rookie0** [comment]
循坏 302 是由于 Nextcloud 的安全策略，看 [nextcloud/server#2523](https://github.com/nextcloud/server/issues/2523) 是修复了，具体不清楚，应该是需要在哪里进行配置

简单粗暴的话，可以在 `apps/files_sharing/lib/Controller/ShareController.php` 中给方法 `downloadShare` 添加注释 `@NoSameSiteCookieRequired`

当然，也可以直接用这个插件，加个CDN域配置回源就行

**Comment by SakuraLove** [comment]
好的，我看看
