### ISSUE TITLE
NexCloud Sharing-Path: HTTP Error 403

### ISSUE THREAD

**Issue by MMezgu3354dhbjc** [rookie0/nextcloud-sharing-path#30]
Hey there, 

it seems that now this is nor working anymore in our nextcloud (and others too).

This Path was working fine for a longer period. But now we get an error.
[https://data.ge-komm.de/apps/sharingpath/gk/portal/uploads/Ahaus/100NIKON/DSCN9407.JPG](https://data.ge-komm.de/apps/sharingpath/gk/portal/uploads/Ahaus/100NIKON/DSCN9407.JPG)

HTTP Error 403

This happened to two separate accounts/servers. Maybe an update on nextcloud.
Hosted at Hetzner.com

Any help?

Best wishes Arne

**Comment by rookie0** [comment]
Sorry for that, please check `Settings` > `Sharing`(Administration & Personal) > `Sharing Path` > `Enable sharing path` according [http_response_code(403)](https://github.com/rookie0/nextcloud-sharing-path/blob/master/lib/Controller/PathController.php#L84).
