### ISSUE TITLE
Chrome issues accessing shared files...

### ISSUE THREAD

**Issue by sushibear** [rookie0/nextcloud-sharing-path#31]
This is just a blind guess and I am not sure if it by any chance could be the problem of this plugin, but is there a possibility that the MIME types set in Nextcloud and the MIME types set in Apache are completely ignored by the browser when accessing files thru a shared path?

I have problems for instance loading JPGs, PNGs or .js files from a share and get different behaviour loading these file types in different browsers.

Any ideas? 

Could be related to: https://github.com/rookie0/nextcloud-sharing-path/issues/21#issue-628119373

**Comment by rookie0** [comment]
This app output Content-Type use nextcloud [MimeTypeDetector](https://github.com/rookie0/nextcloud-sharing-path/blob/master/lib/Controller/PathController.php#L207), please check the file real type at nextcloud data storage place(default at nextcloud-install-path/data/username/files/file-path).

**Comment by sushibear** [comment]
OK .. so I checked the type in the file system, which is image/png.

Curl spit out the following as well:
`curl -I http://myserver:port/apps/sharingpath/test/Photos/6bf2e4728956595bf6dc75bf126.png
HTTP/1.1 200 OK
Date: Thu, 29 Apr 2021 08:26:55 GMT
Server: Apache/2.4.38 (Debian)
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Powered-By: PHP/7.4.15
Set-Cookie: oc5v6wn0om4x=5924f6c003b8fcd5da086b03c57a7c88; path=/; HttpOnly; SameSite=Lax
Expires: 0
Cache-Control: must-revalidate, post-check=0, pre-check=0
Pragma: public
Set-Cookie: oc_sessionPassphrase=E5ss94e8e2kQVC8hZZZqKmgFLclur%2B8XzpKj0ZwxqJ4XVabdioWQFK7xWZegHaVwcryuN6l0crjyNRRmgkCFxZaHsKoHqI%2BT6sUXt5lUcaFWGzrslLmtKJXrjAYBjif5; path=/; HttpOnly; SameSite=Lax
Set-Cookie: oc5v6wn0om4x=1e43f853aafb76b787929355f877f984; path=/; HttpOnly; SameSite=Lax
Content-Security-Policy: default-src 'self'; script-src 'self' 'nonce-MThlQjVGTDYzeTJocFp3SHFtZDJMZWdZNFUwaHpKd2RBck5Bd0lBS3hHUT06bllIUnBocWpzSHZId2NoOThCUVJIOThwdEh3WmhkcC9UZkVxaExkRWxBbz0='; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *; object-src 'none'; base-uri 'self';
Set-Cookie: nc_sameSiteCookielax=true; path=/; httponly;expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax
Set-Cookie: nc_sameSiteCookiestrict=true; path=/; httponly;expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict
Content-Transfer-Encoding: binary
Content-Length: 2180227
Content-Type: image/png`


Safari, Firefox and Postman are properly show the image in the browser, only Chrome wants to download the shared files.

Chrome Warning:
`Resource interpreted as Document but transferred with MIME type application/octet-stream`

Chrome Headers:
`HTTP/1.1 200 OK
Date: Thu, 29 Apr 2021 08:30:30 GMT
Server: Apache/2.4.38 (Debian)
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Powered-By: PHP/7.4.15
Expires: 0
Cache-Control: must-revalidate, post-check=0, pre-check=0
Pragma: public
Content-Security-Policy: default-src 'self'; script-src 'self' 'nonce-UStSODBTZ0t4RnViWTU3dTFwZnEvVXdxbGwvdmp2b0FBRnpkTERhb3UzQT06Q1owZTVFOHpzQ24wSzdHTGhQYUlySHhJOFRlbDlLczBVaSs4ZlhUdDZDaz0='; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *; object-src 'none'; base-uri 'self';
Content-Transfer-Encoding: binary
Content-Length: 0
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: text/plain
access-control-allow-origin: *
access-control-allow-methods: GET, HEAD, POST, PUT, PATCH, DELETE, OPTIONS
access-control-allow-headers: *
access-control-expose-headers: *`

Do you have any idea why Chrome gets the wrong mime type from the cloud when I try to access the file?

**Comment by sushibear** [comment]
I think I got something... even though this is just a hint of what's going on here...

When I try to access a file thru sharing path it calls this script on the server: `/var/www/html/lib/private/Files/Storage/Local.php` 
on Chrome with the following params:
`/var/www/html/data/admin/files/Photos/6bf2e4728956595bf6dc75bf126.png`

The file is however NOT inside the admin users directory but in a dir of a user named test.
It seems as if the other browsers are doing something different here getting the path right.

**Comment by rookie0** [comment]
Maybe related to https://github.com/rookie0/nextcloud-sharing-path/issues/23#issuecomment-679144870, this app(or nextcloud) got wrong user.

I will follow up.

**Comment by sushibear** [comment]
Hey ..  any news on this issue?  
Really does look like it might be releated to #23

**Comment by rookie0** [comment]
Fixed in [v0.4.3](https://github.com/rookie0/nextcloud-sharing-path/releases/tag/v0.4.3)
