### ISSUE TITLE
sharing path: HTTP Error 404 Not Found 

### ISSUE THREAD

**Issue by msngupta** [rookie0/nextcloud-sharing-path#32]
When I try to access the shared file using the link generated by "sharing path" extension (such as the link below), I receive a 404 Not found error. 
https://nextcloud.xyz/apps/sharingpath/admin/Nextcloud.png

Where as a link such as this is accessible.
https://nextcloud.xyz/apps/files

I tried it on various files and accounts. I made sure that the "Enable sharing path" option is checked. 

Nextcloud version: 20.0.7
Sharing Path app version: 0.3.0

I could not see any error in the nextcloud logs.
Please let me know how to fix this issue.

Thanks,

**Comment by rookie0** [comment]
Please check do you have share the file, or you can upgrade to v0.4.0 and set the `Sharing folder`.

**Comment by sushibear** [comment]
Could be related to: #33
