### ISSUE TITLE
Default setting is not respected

### ISSUE THREAD

**Issue by sushibear** [rookie0/nextcloud-sharing-path#33]
I discovered that even if the administrator gobal setting for sharing path is checked, and the users personal sharing settings are reading "Enable sharing path Set by admin" and their checkbox is checked, the default setting is not respected and getting a file from a users shared path, results in a 403.

With other words, the default setting has currently no effect.

Following this procedure you can test this yourself:

1. Login as administrator and go to settings > administration/sharing > turn on Default Enable sharing path
2. Create a new user
3. Login as new user and setup a shared directory, upload a file to this directory you want to share
4. Right click the file inside the share directory, copy sharing path and try it inside a new tab
5. Result is a 403
6. Go back to the users personal share settings and uncheck the sharing path checkbox and then check it again
7. Now try to access the file again and voila..  it works as expected :/

**Comment by sushibear** [comment]
Any help with this?

**Comment by sushibear** [comment]
Looks like this is not returning any value IF the user did not uncheck and check sharing path in his settings.
https://github.com/rookie0/nextcloud-sharing-path/blob/8d0c5994ef7c8d5e04ecce834f1bdcfb0592a71e/lib/Controller/PathController.php#L83

**Comment by rookie0** [comment]
Sorry for the late reply, i will take a look later and welcome submit a PR.

**Comment by sushibear** [comment]
> Sorry for the late reply, i will take a look later and welcome submit a PR.

I would but I am currently not sure what triggers this problem. Would be great if you could take a look as well. :)

**Comment by sushibear** [comment]
Did you have a chance to look into this? I am sure some issues are releated to this one.

**Comment by rookie0** [comment]
@sushibear So sorry for this late fix, please take a look [v0.4.1 - nightly](https://github.com/rookie0/nextcloud-sharing-path/releases/tag/v0.4.1)
