### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by ghost** [rookie0/nextcloud-sharing-path#35]
Whenever I go to the sharing path URL, it gives me a blank page without any errors.

App is enabled in settings.

**Comment by sushibear** [comment]
Did you check your logs in _Nextcloud > Settings > Administration > Logging_ ?

**Comment by 0ghj04hjyg9045** [comment]
I somehow fixed it? I need to create a share link first, then copy the sharing path otherwise it will show a blank screen.
