### ISSUE TITLE
No configuration screen

### ISSUE THREAD

**Issue by brucealthompson** [rookie0/nextcloud-sharing-path#36]
I would like to try this app. Unfortunately, it does not work in Nextcloud 21.

The configuration screen for this app is essentially blank. It does not include the copy prefix or sharing folder text boxes. See the screen capture below.

![Capture](https://user-images.githubusercontent.com/35532447/120122509-704f4400-c166-11eb-8cfa-65147fbefeef.PNG)

**Comment by Basserra** [comment]
I thought _Sharing Path_ didn't have/need configuration. You simply share your file the normal way, then, click the _Sharing Path_ button on the file itself. I can no longer test as I'm running NC22 now and it is not compatible, which is a whole-nother issue now.

**Comment by rookie0** [comment]
Please upgrade to [v0.4.3](https://github.com/rookie0/nextcloud-sharing-path/releases/tag/v0.4.3), the configuration can set since v0.4.0-nightly.
