### ISSUE TITLE
typos in description in apps.nextcloud.com

### ISSUE THREAD

**Issue by alexanderdd** [rookie0/nextcloud-sharing-path#40]
Hello,

in https://apps.nextcloud.com/apps/sharingpath 
> Now you cau use nextcloud as 

-> can
-> Nextcloud (always capitalized)

Maybe improve the description a little bit. I as a beginner did not understand what the app does. Maybe include an example.

**Comment by rookie0** [comment]
Thanks, will fix in the next release.
