### ISSUE TITLE
Open shared path is a 404 error

### ISSUE THREAD

**Issue by soyohoo** [rookie0/nextcloud-sharing-path#42]
In version 22.1.0, the plugin is 0.4.3, 
the shared path is set to: https://nextcloud.host.com/apps/sharingpath/admin, 
and the folder is set to: public/pic.
Open shared path is a 404 error,nginx

![1640159586(1)](https://user-images.githubusercontent.com/53852051/147056110-de80059f-533b-437e-b82d-1a746ac2f099.png)

**Comment by rookie0** [comment]
Duplicate of #39.

**Comment by oghin7** [comment]
In version 23  i   have installed Sharing Path 0.4.3  i got error 404.  can you please tell me the older version may work?
