### ISSUE TITLE
Overwrite the download link on share page to view the directory

### ISSUE THREAD

**Issue by Nyaasu66** [rookie0/nextcloud-sharing-path#46]
如题，因为推测作者应该是国人就不发英文了。

我想要问的是，
这个插件可不可以在分享页面覆盖重写下载链接，
以达到查看目录的效果，
这样对使用CDN来说更有意义，
不需要一个文件一个链接来共享。

应该和 #14 是类似的问题

**Comment by Nyaasu66** [comment]
似乎已经有插件可以达到重写下载地址的作用

https://apps.nextcloud.com/apps/sharerenamer

**Comment by Nyaasu66** [comment]
> 似乎已经有插件可以达到重写下载地址的作用
> 
> [apps.nextcloud.com/apps/sharerenamer](https://apps.nextcloud.com/apps/sharerenamer)

不幸的是，我可能搞错了，这个插件只能修改分享页面地址的链接

**Comment by rookie0** [comment]
没明白 是要 dir listing 的效果还是 redirect 的效果？
listing 这个应该不会支持 redirect 这个跟这个插件的定位不太符

**Comment by Nyaasu66** [comment]
是想要 redirect 的效果。

就比如我打开一个 NC 的分享链接，选择一个文件点击下载按钮，
<img width="877" alt="image" src="https://user-images.githubusercontent.com/32192232/185029042-80943e3e-52e9-4ae3-bf96-20346dd0c863.png">

这里请求的是 GET `https://next.cloud/flac/download?path=a&files=b&downloadStartSecret=c`

我是希望这里的请求能直接替换成使用本插件转换的静态链接 `http://next.cloud/apps/sharingpath/User/a/b`

如果不太符合的话，那打扰了😶

**Comment by rookie0** [comment]
嗯 做不到
原分享链接是 nextcloud 自带的 sharing 处理的 要做的话得 hack 他的逻辑

**Comment by Nyaasu66** [comment]
原来如此，看起来是非常麻烦，还是多谢了
