### ISSUE TITLE
Support localization

### ISSUE THREAD

**Issue by p-bo** [rookie0/nextcloud-sharing-path#47]
Hello,
Would it be possible to follow instructions on:
https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html
...and make your app more accessible for non-English speakers please?

Thanks :-)

**Comment by rookie0** [comment]
Already have basic support.

**Comment by p-bo** [comment]
@rookie0 That's great - would it be possible to hint, where to add translations then please (l10n directory with any .js and .json files seems to be not present)?

**Comment by p-bo** [comment]
@rookie0 sorry for bothering with this, but would it be possible to explain that basic support please (to be able to use it as translators)?

**Comment by rookie0** [comment]
@p-bo See https://github.com/rookie0/nextcloud-sharing-path/blob/master/templates/settings/personal.php#L49(except the notice info), https://github.com/rookie0/nextcloud-sharing-path/blob/master/js/script.js#L18

This use nextcloud default translation, and you can add translations follow this https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html#manual-translation.
