### ISSUE TITLE
Hide username in path?

### ISSUE THREAD

**Issue by Gatak** [rookie0/nextcloud-sharing-path#6]
This is a really nice little app. Makes sharing files to friends easy :)
However to use as a CDN I'd really like to hide the username from the path. Is that possible somehow? Perhaps by sharing in a group folder? 

https://example.net/index.php/apps/sharingpath/someuser/Temp/12474335.tiff

**Comment by rookie0** [comment]
You can use nginx rewrite to hide the username.
```
location ~ /prefix-you-like/ {
    rewrite ^/prefix-you-like/(.*)$ /index.php/apps/sharingpath/username/$1 break;
    proxy_pass http://localhost;
}
```
