### ISSUE TITLE
This does not work at all

### ISSUE THREAD

**Issue by srednax** [rookie0/nextcloud-sharing-path#7]
Using NC 16.0.3. There is nothing about this in the share menu. Zilsh.

**Comment by rookie0** [comment]
What do you mean `share menu`, please check this app `Sharing Path` is enabled first(is exist in `Active apps`), and the action is `Open Sharing Path` that you can find in file right click menu or dropdown menu.

**Comment by srednax** [comment]
Well, I figured it out, although in the beginning of using the plugin, an image in my root folder did not have the "open shared path" item in the context menu.
I believe you should put your UI in the share panel/menu, to make things easier to understand, and offer "copy shared path" instead of "open shared path" (similar to the share function). Anyway, I'm happy that the plugin actually does provide a functional path that I can use on my website, so I can avoid keeping two copies of an image :)

**Comment by rookie0** [comment]
Updated in v0.0.3.
